spring.config.activate.on-profile: release

spring:
  datasource:
    url: ${MYSQL_DATASOURCE_URL}
    username: ${MYSQL_DATASOURCE_USERNAME}
    password: ${MYSQL_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    open-in-view: false
  data:
    redis:
      host: ${REDIS_DATASOURCE_HOST}
      port: ${REDIS_DATASOURCE_PORT}
  mail:
    host: ${RELEASE_MAIL_HOST}
    port: 587
    username: ${RELEASE_MAIL_USERNAME}
    password: ${RELEASE_MAIL_PASSWORD}
    from: ${RELEASE_MAIL_SENDER}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
            redirect-uri: https://areyouhere.today/api/login/oauth2/code/google
slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}

cors:
  allowed-origins: https://areyouhere.today, https://www.areyouhere.today

cookie:
    encode: ${SECRET_KEY}

