spring.config.activate.on-profile: develop

spring:
  datasource:
    url: ${MYSQL_DATASOURCE_URL}
    username: ${MYSQL_DATASOURCE_USERNAME}
    password: ${MYSQL_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    open-in-view: false
  data:
    redis:
      host: ${REDIS_DATASOURCE_HOST}
      port: ${REDIS_DATASOURCE_PORT}
  mail:
    host: ${DEV_MAIL_HOST}
    port: 587
    username: ${DEV_MAIL_USERNAME}
    password: ${DEV_MAIL_PASSWORD}
    from: ${DEV_MAIL_SENDER}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
            redirect-uri: https://dev.areyouhere.today/api/login/oauth2/code/google

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}

cors:
  allowed-origins: https://dev.areyouhere.today, https://dev.www.areyouhere.today
cookie:
  encode: ${SECRET_KEY}

