spring.config.activate.on-profile: local

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/areyouhere
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:

      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: null
    port: 1
    username: null
    password: null
    from: null
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
            redirect-uri: https://localhost:8080/api/login/oauth2/code/google
logging:
  level:
    root: debug

cors:
  allowed-origins: http://localhost:5173

cookie:
  encode: TEMP
